<?php

$keyId = 'rzp_live_HsE9LWd7JzPX0U';

if($_POST['amo']==999){
    $cor="corse1.html"    ;
}
if($_POST['amo']==14999){
    $cor="corse1.html"    ;
}
if($_POST['amo']==24999){
    $cor="corse1.html"    ;
}

?>
<form action="<?php echo $cor;?>" method="POST">
    <script src="https://checkout.razorpay.com/v1/checkout.js" 
    data-key="<?php echo $keyId;?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys 
    data-amount="<?php echo $_POST['amo']*100;?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35. 
    data-currency="INR" // You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account 
    data-id="<?php echo 'OID'.rand(10,100).'END';?>" // Replace with the order_id generated by you in the backend. 
    data-buttontext="Pay with Razorpay" 
    data-name="Deepta Manohar" 
    data-description="Deepta Manohar" 
    data-image="5.png" 
    data-prefill.name="<?php echo $_POST['name']?>" 
    data-prefill.email="<?php echo $_POST['email']?>" 
    data-prefill.contact="<?php echo $_POST['phone']?>" 
    data-theme.color="#528FF0">
</script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>

<style>
.razorpay-payment-button{
    position: absolute;
  top: 50%;
  left: 50%;
  -ms-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
 }
 .razorpay-payment-button {
   height: 10%;
   border-radius: 5px;
   border: none;
   color: #fff;
   font-size: 18px;
   font-weight: 500;
   letter-spacing: 1px;
   cursor: pointer;
   transition: all 0.3s ease;
   background: #528FF0;
 }
</style>
<script type="text/javascript">
    $(document).ready(function(){
        $('razorpay-payment-button').click();
    });
</script>